language: rust
sudo: required
dist: trusty
addons:
    apt:
        packages:
            - libssl-dev
cache: cargo
rust:
  - nightly

after_success: |
  # bash <(curl https://raw.githubusercontent.com/xd009642/tarpaulin/master/travis-install.sh)
  cargo install cargo-tarpaulin
  # Uncomment the following line for coveralls.io
  RAYON_NUM_THREADS=1 cargo tarpaulin --all --ciserver travis-ci --coveralls $TRAVIS_JOB_ID

  # Uncomment the following two lines create and upload a report for codecov.io
  # cargo tarpaulin --out Xml
  # bash <(curl -s https://codecov.io/bash)
