name: Rust

on:
  push:
    branches:
      - "*"
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - stable
          - beta
          - nightly
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.version }}
          override: true
      - name: clean
        run: cargo clean
      - name: build
        run: cargo build --verbose --all-features
        env:
          RUST_BACKTRACE: 1
        if: matrix.version == 'nightly'
      - name: test
        run: cargo test --all-features
        env:
          RUST_BACKTRACE: 1